// automatic dialog
let anviEnda = [
    "",
    "ANVI:",
    "ANVI:",
    "ANVI:",
    "ANVI:",
    "ANVI:",
    "",
    "",
    "ANVI:",
    "",
    "",
    "ANVI:",
    "ANVI:",
    "ANVI:",
    "",
    "ANVI:",
    "ANVI:",
    "",
    "ANVI:",
    "",
    "ANVI:",
    "",
    "",
    "ANVI:",
    "ANVI:",
    "ANVI:",
    "ANVI:",
    "ANVI:",
    "",
    "ANVI:",
    "",
    "ANVI:",
    "",
    "",
    ""
]
let anviEndb = [
    "[ ANVI helps you walk SUZY outside. she gently places SUZY in the backseat of your car. ]",
    "...",
    "haven't seen SUZY in a while. it was nice hanging out with her again.",
    "even though she was throwing up for most of it. haha.",
    "...",
    "anyway. i'm gonna head back in. i think you've got this handled.",
    "[ ANVI turns to go back into the house. ]",
    "CHOICE_wait.^0",
    "...",
    "[ ANVI turns back to look at you. she raises an eyebrow. ]",
    "CHOICE_i'm sorry.^0",
    "...",
    "well, i never thought i'd live to see the day.",
    "sorry for what, exactly?",
    "CHOICE_for shutting you out.^0_for never saying what i meant.^0_for being a bad boyfriend.^0",
    "very true.",
    "why now, though? why not last week, or last year, or when we broke up freshman year?",
    "CHOICE_well, i might never see you again.^0",
    "all the more reason to keep quiet.",
    "CHOICE_i just don't want to leave things this way forever.^0",
    "so you're not just trying to win me back?",
    "CHOICE_god, no. i don't think you want me back.^0",
    "[ ANVI laughs. ]",
    "you're right. i've had my fill.",
    "...",
    "thank you for saying all that, though. i'm glad you've grown up a little.",
    "god help the next girl if you hadn't.",
    "(or guy. or whoever.)",
    "CHOICE_[ curious eyebrow raise. ]^0",
    "hey, we're going off to college. broadening our horizons and whatnot. you never know.",
    "CHOICE_well, then, good luck to your next guy. (or girl. or whoever.)^0",
    "good luck indeed.",
    "[ ANVI heads back into the house, and you get in your car and drive home with SUZY, who's fast asleep in the back seat. ]",
    "[ ... ]",
    "[ that party wasn't so bad after all. ]"
]
let ryanEnda = [
    "",
    "RYAN:",
    "RYAN:",
    "RYAN:",
    "RYAN:",
    "RYAN:",
    "",
    "RYAN:",
    "RYAN:",
    "",
    "RYAN:",
    "RYAN:",
    "",
    "RYAN:",
    "RYAN:",
    "RYAN:",
    "RYAN:",
    "RYAN:",
    "RYAN:",
    "",
    "RYAN:",
    "",
    "RYAN:",
    "",
    "RYAN:",
    "RYAN:",
    "RYAN:",
    "RYAN:",
    "RYAN:",
    "",
    "RYAN:",
    "RYAN:",
    "RYAN:",
    "RYAN:",
    "",
    "RYAN:",
    "RYAN:",
    "",
    "",
    "RYAN:",
    "",
    "",
    "",
    ""
]
let ryanEndb = [
    "[ RYAN helps you walk SUZY outside. he gently places SUZY in the backseat of your car. ]",
    "there we go. easy as that.",
    "...",
    "i'd better head back in. i'm sure you've got this covered.",
    "or if you don't, you can always text me. i know you don't have much experience with drinking and stuff.",
    "or you could... not text me, also. that's okay too.",
    "[ a long, awkward silence. RYAN looks at you expectantly. ]",
    "...",
    "sorry. i don't--i'm not--um. i'll just go now.",
    "CHOICE_don't go.^0",
    "!",
    "...why?",
    "CHOICE_i'm sorry.^0",
    "!!!",
    "sorry for... what?",
    "it was my fault, DREW.",
    "i'm the one who confessed. i'm the one who made things weird.",
    "if we drifted apart, it's only because i let it happen.",
    "i MADE it happen.",
    "CHOICE_it's my fault, too.^0",
    "how so?",
    "CHOICE_i kept ignoring you.^0_i avoided you in the halls.^0_i never talked to you, even when we had physics C together this year.^0",
    "it's understandable why you would.",
    "CHOICE_it's not. we were friends. you were just telling the truth.^0",
    "...",
    "i don't know why i told you, anyway.",
    "some part of me just... it, like... had hope, i guess.",
    "i guess it goes without saying that i still feel the same. haha.",
    "but don't worry. i'm not expecting you to suddenly change your mind.",
    "CHOICE_you deserve better, anyway.^0",
    "what!!!",
    "you've gotta be kidding me, dude. you're the total package.",
    "you're thoughtful, you're athletic, you care about your family, you crochet...",
    "and you don't have a TWEETER account... that's a big one.",
    "CHOICE_and i don't text back.^0",
    "okay, well, we can work on that.",
    "or, like. assuming we're friends again, that is...?",
    "CHOICE_yeah, of course.^0",
    "[ RYAN grins. ]",
    "alright, then. text me when you get home. that's your first assignment.",
    "[ RYAN heads back into the house--but not before giving you a wave goodbye. ]",
    "[ you get in your car and drive home with SUZY, who's fast asleep in the back seat. ]",
    "[ ... ]",
    "[ that party wasn't so bad after all. ]"
]
let lisaEnda = [
    "",
    "LISA:",
    "LISA:",
    "",
    "",
    "LISA:",
    "",
    "LISA:",
    "",
    "LISA:",
    "",
    "LISA:",
    "",
    "LISA:",
    "",
    "LISA:",
    "",
    "LISA:",
    "",
    "LISA:",
    "",
    "LISA:",
    "",
    "",
    "LISA:",
    "",
    "LISA:",
    "LISA:",
    "",
    "LISA:",
    "LISA:",
    "",
    "LISA:",
    "LISA:",
    "LISA:",
    "LISA:",
    "",
    "",
    ""
]
let lisaEndb = [
    "[ LISA helps you walk SUZY outside. She gently places SUZY in the backseat of your car. ]",
    "so, um. yeah.",
    "see you in the next life, i guess.",
    "[ LISA turns around to leave. ]",
    "CHOICE_i'm sorry.^0",
    "!",
    "[ LISA turns back to face you. ]",
    "sorry for what, exactly?",
    "CHOICE_kissing you.^0_ghosting you.^0_everything.^0",
    "...",
    "CHOICE_i didn't mean to hurt you.^0",
    "...",
    "CHOICE_i just thought...^0",
    "...",
    "CHOICE_i don't know. i wasn't thinking.^0",
    "...",
    "CHOICE_and i was so scared that you hated me after.^0",
    "...",
    "CHOICE_so i ran away. and that wasn't fair to you.^0",
    "you're right. it wasn't.",
    "CHOICE_there's nothing i can say to fix what i did.^0",
    "that's also true.",
    "CHOICE_but i still want to be a good friend to you.^0",
    "[ LISA smiles. ]",
    "you know what you gotta do, then, right?",
    "CHOICE_stop ghosting you?^0",
    "stop ghosting me.",
    "come on, man. i sent you like four FLOATING BUSINESSMAN EMOJIS in a row.",
    "CHOICE_what am i supposed to do with four FLOATING BUSINESSMAN EMOJIS??^0_[ take out your PHONE and send her a FLOATING BUSINESSMAN EMOJI back. ]^2",
    "i don't know!! pick a different weird EMOJI to send back to me.",
    "or just tell me about your day. that'd be nice, too.^3",
    "[ LISA takes out her phone and laughs. ]",
    "baller.",
    "um. anyway. this was good. i'm glad we got to talk.",
    "i missed you, man.",
    "see you around.",
    "[ LISA goes back into the house. you get in your car and drive home with SUZY, who's fast asleep in the back seat. ]",
    "[ ... ]",
    "[ that party wasn't so bad after all. ]"
]
let suzyEnda = [
    "",
    "SUZY:"
]
let suzyEndb = [
    "[ you walk SUZY outside and guide her in the backseat of your car. ]",
    "i'm gonna throw up houuuuuughghohgguhogu"
]